name: ndtest
channels:
  - conda-forge
dependencies:
  - python=3.6
  - gsl
  - numpy
  - sphinx
  - sphinxcontrib-apidoc
  - cythongsl
  - ipython
  - matplotlib
  - imageio
  - opencv
  - rasterio
  - xarray
  - h5netcdf
  - lxml
  - scipy
